# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Pay_pb2 as Pay__pb2


class SaveStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Pay = channel.unary_unary(
        '/Pay.Save/Pay',
        request_serializer=Pay__pb2.ConsumeReq.SerializeToString,
        response_deserializer=Pay__pb2.ConsumeResp.FromString,
        )


class SaveServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Pay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SaveServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Pay': grpc.unary_unary_rpc_method_handler(
          servicer.Pay,
          request_deserializer=Pay__pb2.ConsumeReq.FromString,
          response_serializer=Pay__pb2.ConsumeResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Pay.Save', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
